### ISSUE TITLE
Legacy access request rate exceeded

### ISSUE THREAD

**Issue by wjmelements** [trusttoken/true-currencies#106]
This seems to be an issue with truffle. It happens when I run `npm test`.

```
> truecoin@1.0.0 test /Users/williammorriss/work/trueusd
> ./test.sh


/Users/williammorriss/work/trueusd/node_modules/truffle-hdwallet-provider/node_modules/web3/lib/web3/httpprovider.js:118
            callback(error, result);
            ^
Error: legacy access request rate exceeded
    at /Users/williammorriss/work/trueusd/node_modules/web3-provider-engine/subproviders/web3.js:15:44
    at XMLHttpRequest.request.onreadystatechange (/Users/williammorriss/work/trueusd/node_modules/truffle-hdwallet-provider/node_modules/web3/lib/web3/httpprovider.js:118:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/williammorriss/work/trueusd/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/Users/williammorriss/work/trueusd/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpResponseEnd (/Users/williammorriss/work/trueusd/node_modules/xhr2/lib/xhr2.js:509:12)
    at IncomingMessage.<anonymous> (/Users/williammorriss/work/trueusd/node_modules/xhr2/lib/xhr2.js:469:24)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by wjmelements** [comment]
It's not clear why web3js does a mainnet request when you use local ganache.

**Comment by wjmelements** [comment]
The extraneous call seems to be `eth_getBlockByNumber`.

**Comment by wjmelements** [comment]
![Screen Shot 2019-11-15 at 1 34 46 PM](https://user-images.githubusercontent.com/799573/68977266-b7f0c380-07ac-11ea-81dc-d99d21b901fb.png)
